version: 1
swift_versions:
  - "5.10"
  - "6.0"
  - "6.1"
  - "6.2"
builder:
  configs:
    - platform: macos-spm
      documentation_targets:
        - CosmoSQLCore
        - CosmoMSSQL
        - CosmoPostgres
        - CosmoMySQL
        - CosmoSQLite
    - platform: linux
      linux_packages:
        - libsqlite3-dev
        - pkg-config
