version: 1
swift_versions:
  - 6.0
builder:
  configs:
    - documentation_targets:
        - CosmoSQLCore
        - CosmoMSSQL
        - CosmoPostgres
        - CosmoMySQL
        - CosmoSQLite
      platforms:
        - android
        - ios
        - macos
        - linux
        - tvos
        - watchos
        - visionos
